name: ali_ai_call
description: "阿里云智能对话插件的Flutter实现，支持iOS和Android平台。提供语音通话、ASR、TTS等功能。"
version: 1.0.1
homepage: https://github.com/MR-MaoJiu/ali_ai_call
repository: https://github.com/MR-MaoJiu/ali_ai_call

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.ali_ai_call
        pluginClass: AliAiCallPlugin
      ios:
        pluginClass: AliAiCallPlugin

