platform :ios, '12.0'

source 'https://github.com/aliyun/aliyun-specs.git'
source 'https://cdn.cocoapods.org/'

target 'Runner' do
  use_frameworks!
  
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
        config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
        
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        config.build_settings['VALID_ARCHS'] = 'arm64 x86_64'
        
        config.build_settings['LD_RUNPATH_SEARCH_PATHS'] = [
          '$(inherited)',
          '@executable_path/Frameworks',
          '@loader_path/Frameworks'
        ]
      end
    end
  end
end 